export const routes = {
	onboardingGetStarted: '/onboarding/get-started',
	onboardingJoinClub: '/onboarding/join-club',
	onboardingPublicClubs: '/onboarding/join-club/public-clubs',
	onboardingStartClub: '/onboarding/start-club',
	onboardingStartClubVideo: '/onboarding/start-club?step=2',
	noClub: '/no-club',
	newClub: '/new-club',
	newClubJoin: '/new-club/join',
	newClubPublicClubs: '/new-club/join/public-clubs',
	newClubStart: '/new-club/start',
	newClubStartVideo: '/new-club/start?step=2',
	feed: '/feed',
	feedMyClubs: '/feed/my-clubs',
	feedGlobal: '/feed/global',
	chat: '/chat',
	profile: '/profile',
	settings: '/settings',
	settingsMediaUploadDev: '/settings/media-upload-dev',
	notifications: '/notifications',
	applications: '/applications',
	applicationsReview: '/applications/review',
	feedback: '/feedback',
	child: '/child',

	profileDetail: (profileId: string) => `/profile/${profileId}`,
	childOverview: (childProfileId: string) => `/child/${childProfileId}`,
	feedbackSubmit: (formId: string, clubId: string) => `/feedback/${formId}/${clubId}`,
	clubHome: (clubId: string) => `/club/${clubId}`,
	clubSessions: (clubId: string) => `/club/${clubId}/sessions`,
	clubProjects: (clubId: string) => `/club/${clubId}/projects`,
	clubMembers: (clubId: string) => `/club/${clubId}/members`,
	clubSettings: (clubId: string) => `/club/${clubId}/settings`,
	sessionDetail: (sessionId: string) => `/session/${sessionId}/activities`,
	projectDetail: (projectId: string) => `/project/${projectId}/overview`,
	applicationReviewDetail: (applicationId: string) => `/applications/review/${applicationId}`,
	// Public club preview (src/routes/clubs/[clubId]): only resolves discoverable clubs.
	publicClubPreview: (clubId: string) => `/clubs/${clubId}`,
	activityBooklet: '/activity-booklet',
	activityBookletDetail: (activityId: string) => `/activity-booklet/${activityId}`
} as const;
